### PR TITLE
fixed traversierung an output 

### LINKED ISSUE #8: Traversing not working
- brackets at the wrong position (infix)
- prefix and postfix probably also not working correct

### PR DESCRIPTION
**Pull request by carlFelixSchlass**
output strings are now correct 

spacings are also nice

### CODE REVIEW

File: src/Number.hpp [hunk 1]
```diff
@@ -40,16 +40,16 @@ class Number : public Token
     
     string prefix() 
 	{
-         return " " + m_value + " ";  // remove this line
+         return m_value + " ";  // remove this line
     }
```
Comment (janniklth) [inline src/Number.hpp:44]: add paragraph

File: src/Number.hpp [hunk 2]
```diff
@@ -40,16 +40,16 @@ class Number : public Token
...
     string infix()
     {
-        return " " + m_value + " ";  // remove this line
+        return m_value;  // remove this line
     }
```
Comment (janniklth) [inline src/Number.hpp:49]: change tabs

File: src/Operator.hpp
Comment (janniklth) [inline src/Operator.hpp:1]: - edit var naming (use lowercase and underscore
- change tabs (line 75)

**Review by janniklth — APPROVED** [review]
